export interface Performer {
  name: string
  email: string | null
}

export interface ContactGroup {
  id: string
  label: string
  performers: Performer[]
}

export const CONTACT_GROUPS: ContactGroup[] = [
  {
    id: "core-cast",
    label: "Core Cast",
    performers: [
      { name: "Alex Fernie", email: "alfernie@gmail.com" },
      { name: "Alex Song-Xia", email: "alexsongxia@gmail.com" },
      { name: "Alexis Rhiannon", email: "alexis.rhiannon@gmail.com" },
      { name: "Aman Adumer", email: "adumera@gmail.com" },
      { name: "Betsy Sodaro", email: "betsysodaro@gmail.com" },
      { name: "Brian Huskey", email: "brian.huskey@mac.com" },
      { name: "Carl Tart", email: "carldtart@gmail.com" },
      { name: "Chris Renfro", email: "christopher.a.renfro@gmail.com" },
      { name: "Corin Wells", email: "charity.corin@gmail.com" },
      { name: "Dave Theune", email: "theoutlawbiker@gmail.com" },
      { name: "Devin Field", email: "thatdevinfield@gmail.com" },
      { name: "Dhruv Uday Singh", email: "dhruvudaysingh@gmail.com" },
      { name: "Echo Kellum", email: "darthecho@yahoo.com" },
      { name: "Edgar Momplaisir", email: "edgar.momplaisir@gmail.com" },
      { name: "Hillary Anne Matthews", email: "hillaryannematthews@gmail.com" },
      { name: "Jacob Wysocki", email: "jacobwysocki@gmail.com" },
      { name: "James Mannion", email: "jamespmannion@gmail.com" },
      { name: "Jeremy Culhane", email: "jeremy.c.culhane@gmail.com" },
      { name: "Joe Wengert", email: "joe.wengert@gmail.com" },
      { name: "Jordan Myrick", email: "jordanmyr1ck@gmail.com" },
      { name: "Kale Hills", email: "kale@ucbcomedy.com" },
      { name: "Kimia Behpoornia", email: "kbehpoornia@gmail.com" },
      { name: "Lou Wilson", email: "louwilzon@gmail.com" },
      { name: "Mary Holland", email: "mholland85@gmail.com" },
      { name: "Monique Moses", email: "monique.moses@gmail.com" },
      { name: "Oscar Montoya", email: "monoscar@gmail.com" },
      { name: "Owen Burke", email: "owenburke@me.com" },
      { name: "Pam Murphy", email: "murphy.pam.m@gmail.com" },
      { name: "Patrick McDonald", email: "patrick.f.mcdonald@gmail.com" },
      { name: "Paul Welsh", email: "pb.welsh@gmail.com" },
      { name: "Payam Banifaz", email: "peterbanifaz@gmail.com" },
      { name: "Phil Jackson", email: "pjack12@gmail.com" },
      { name: "Rachel Pegram", email: "rachel.a.pegram@gmail.com" },
      { name: "Rekha Shankar", email: "rekhalshankar@gmail.com" },
      { name: "Rob Huebel", email: "thisisrobhuebel@gmail.com" },
      { name: "Ruha Taslimi", email: "ruhataslimi@gmail.com" },
      { name: "Shaun Diston", email: "shaundiston@gmail.com" },
      { name: "Suzi Barrett", email: "suzibarrett@gmail.com" },
      { name: "Vic Michaelis", email: "vicmmic@gmail.com" },
      { name: "Zac Oyama", email: "zatcheloyama@gmail.com" },
      { name: "Zeke Nicholson", email: "isaaczekenicholson@gmail.com" },
    ],
  },
  {
    id: "wild-card",
    label: "Wild Card",
    performers: [
      { name: "Alex Berg", email: "bergsandwich@gmail.com" },
      { name: "Allyn Pintal", email: "allynpintal@ucbcomedy.com" },
      { name: "Angela Giarratana", email: "angelagiarratana2@gmail.com" },
      { name: "Becky Drysdale", email: "rebeccadrysdale@me.com" },
      { name: "Beth Appel", email: "beth.appel@gmail.com" },
      { name: "Caroline Cotter", email: "caroline.cotter2@gmail.com" },
      { name: "Caroline Martin", email: "Caroline.Fiona.Martin@gmail.com" },
      { name: "Dan Gregor", email: "gregorda@gmail.com" },
      { name: "ER Fightmaster", email: "erfightmaster@gmail.com" },
      { name: "Heather Anne Campbell", email: "heather.anne.campbell@gmail.com" },
      { name: "Jacquis Neal", email: "jacquisneal@gmail.com" },
      { name: "James III", email: "james3rdcomedy@gmail.com" },
      { name: "Jerah Milligan", email: "jerah.milligan@gmail.com" },
      { name: "John Gemberling", email: "gemberloins@gmail.com" },
      { name: "Lauren Adams", email: "laurcadams@gmail.com" },
      { name: "Lyndsey Frank", email: "lyndseybfrank@gmail.com" },
      { name: "Mary Anthony", email: "maryeanthony1@gmail.com" },
      { name: "Monika Smith", email: "missmonikasmith@gmail.com" },
      { name: "Mookie Blaiklock", email: "mblaiklock@gmail.com" },
      { name: "Moujan Zolfghari", email: "moujanz@gmail.com" },
      { name: "Nick Mandernach", email: "nicholasmandernach@gmail.com" },
      { name: "Ryan Barton", email: "ryanbarton15@gmail.com" },
      { name: "Toni Charline", email: "tonicharline@gmail.com" },
      { name: "Zach Reino", email: "zreino@gmail.com" },
    ],
  },
  {
    id: "sub-list",
    label: "Sub List",
    performers: [
      { name: "Nnamdi Ngwe", email: "nnamdingwe@gmail.com" },
      { name: "Matt Newell", email: "matt.newell@ucbcomedy.com" },
      { name: "Ify Nwadiwe", email: "inwadiwe@thatblacknerd.com" },
      { name: "Carlos Santos", email: "CARLOS.SANTOSPR@gmail.com" },
      { name: "Madeline Walter", email: "madeline.walter@gmail.com" },
      { name: "Laura Chinn", email: "lauracchinn@gmail.com" },
      { name: "Keisha Zollar", email: "KeishaZollar@gmail.com" },
      { name: "Mano Agapion", email: "manoagapion@gmail.com" },
      { name: "Nina Concepcion", email: "ninamconcepcion@gmail.com" },
      { name: "Will Hines", email: "whines@gmail.com" },
      { name: "Ryan Rosenberg", email: "ryanarosenberg@gmail.com" },
      { name: "Ronnie Adrian", email: "ronnieadriancom@gmail.com" },
      { name: "Marcy Jarreau", email: "marcylane@gmail.com" },
      { name: "Sean Conroy", email: "swarmsean@gmail.com" },
      { name: "Casey Feigh", email: "caseyfeigh@gmail.com" },
      { name: "Dan Lippert", email: "dan.lippert@gmail.com" },
      { name: "Jessica McKenna", email: "jessimcca@gmail.com" },
      { name: "Ally Beardsley", email: "allybeardsley@gmail.com" },
      { name: "Ali Ghandour", email: "aghandour@gmail.com" },
      { name: "Alison Rich", email: "alison.h.rich@gmail.com" },
      { name: "Anne Lane", email: "annelouiselane@gmail.com" },
      { name: "Don Fanelli", email: "fadonz@gmail.com" },
      { name: "Frank Garcia-Hejl", email: "frankgarciahejl@gmail.com" },
      { name: "Greg Hess", email: "greghess@gmail.com" },
      { name: "Holly Laurent", email: "hclaurent@gmail.com" },
      { name: "James Mastraieni", email: "james.mastraieni@gmail.com" },
      { name: "Jean Villepique", email: "thejeanmachine@mac.com" },
      { name: "Jen D'Angelo", email: "jsdangelo@gmail.com" },
      { name: "Jessica Elaina Eason", email: "jesspatsox@gmail.com" },
      { name: "Jiavani", email: "jiavani.linayao@gmail.com" },
      { name: "Julia Meltzer", email: "juliaburttmeltzer@gmail.com" },
      { name: "Gilli Nissim", email: "gilli.nissim@gmail.com" },
      { name: "Londale Theus Jr", email: "lmtboogie@gmail.com" },
      { name: "Matt Apodaca", email: "mattapodaca@gmail.com" },
      { name: "Sarah Claspell", email: "sarahbc@gmail.com" },
      { name: "Seth Morris", email: "sethismorris@gmail.com" },
      { name: "Talia Tabin", email: "talia.tabin@gmail.com" },
      { name: "Victoria Longwell", email: "val5008@gmail.com" },
    ],
  },
  {
    id: "drop-ins",
    label: "Drop-Ins",
    performers: [
      { name: "Laci Mosley", email: "lacirisemosley@gmail.com" },
      { name: "Lisa Gilroy", email: "lisa.m.gilroy@gmail.com" },
      { name: "Lauren Lapkus", email: "lauren.lapkus@gmail.com" },
      { name: "Andy Daly", email: "andrewdaly@me.com" },
      { name: "Anthony King", email: "theanthonyking@gmail.com" },
      { name: "Arden Myrin", email: "ardenmyrin@gmail.com" },
      { name: "Bobby Moynihan", email: "moynihan19@gmail.com" },
      { name: "Brandon Scott Jones", email: "jones.brandonscott@gmail.com" },
      { name: "Brennan Lee Mulligan", email: "brennanleemulligan@gmail.com" },
      { name: "Colton Dunn", email: "colton.dunn@gmail.com" },
      { name: "Connor Ratliff", email: "connorratliff@gmail.com" },
      { name: "D'Arcy Carden", email: "darcycarden@gmail.com" },
      { name: "Drew Tarver", email: "drew.tarver@gmail.com" },
      { name: "Edi Patterson", email: null },
      { name: "Ego Nwodim", email: "eknwodim@gmail.com" },
      { name: "Eugene Cordero", email: "ecorderoiv@gmail.com" },
      { name: "Fran Gillespie", email: "gillespie.fran@gmail.com" },
      { name: "Gil Ozeri", email: "gilozeri@gmail.com" },
      { name: "Ian Brennan", email: "iancbrennan@yahoo.com" },
      { name: "Ian Roberts", email: "baganga@aol.com" },
      { name: "Jon Daly", email: "joncdaly@gmail.com" },
      { name: "Jason Mantzoukas", email: "jmantzoukas@gmail.com" },
      { name: "Jon Gabrus", email: "gabrus@gmail.com" },
      { name: "Katie Dippold", email: "katiedippold@gmail.com" },
      { name: "Kirby Howell-Baptiste", email: "kirbyhowellbaptiste@gmail.com" },
      { name: "Lennon Parham", email: "lparham10@gmail.com" },
      { name: "Lily Sullivan", email: "lilycsullivan@gmail.com" },
      { name: "Matt Besser", email: "mattbesser67@gmail.com" },
      { name: "Matt Walsh", email: "ucbwalshy@aol.com" },
      { name: "Mike Mitchell", email: "mmitc47579@aol.com" },
      { name: "Mike O'Brien", email: null },
      { name: "Neil Campbell", email: "nbcampbell@gmail.com" },
      { name: "Neil Casey", email: "notneilcasey@mac.com" },
      { name: "Nicole Byer", email: "nicolebyer@gmail.com" },
      { name: "Nicole Parker", email: "nicoleparkerredford@gmail.com" },
      { name: "Paul Rust", email: "paul.rust@gmail.com" },
      { name: "Paul Scheer", email: "paulisnotajerk@me.com" },
      { name: "Paul F. Tompkins", email: "chalkstripe@gmail.com" },
      { name: "Sasheer Zamata", email: "sasheer1@gmail.com" },
      { name: "Stephanie Allynne", email: "stephanieallynne@gmail.com" },
      { name: "Sudi Green", email: null },
      { name: "Tawny Newsome", email: null },
      { name: "Tim Baltz", email: "btimothee1111@gmail.com" },
      { name: "Zach Woods", email: "zachwoods55@yahoo.com" },
    ],
  },
  {
    id: "test-group",
    label: "Test Group",
    performers: [
      { name: "Andres Parada", email: "andresparadacomedy@gmail.com" },
      { name: "Anna Garcia", email: "annalynnegarcia@gmail.com" },
      { name: "Anna Rajo", email: "anna.rajomiller@gmail.com" },
      { name: "Chad Westbrook", email: "cmwestbrook22@gmail.com" },
      { name: "Chris Tcholakian", email: null },
      { name: "Collin McGurk", email: null },
      { name: "DJ Mausner", email: "mausnerdj@gmail.com" },
      { name: "Eli Gonzalez", email: "eli.j.gonzalez@gmail.com" },
      { name: "Greg Roman", email: "ghr.greg@gmail.com" },
      { name: "Jack Brown", email: "brown7790jjb@gmail.com" },
      { name: "James Jellin", email: null },
      { name: "Joe Fahey", email: "joefaheycomedy@gmail.com" },
      { name: "Josh Brekhus", email: "joshbrekhus@gmail.com" },
      { name: "Lauren Holt", email: "leholt312@gmail.com" },
      { name: "Lilan Bowden", email: "lilan.bowden@gmail.com" },
      { name: "Mia Schauffler", email: "mia.schauffler@gmail.com" },
      { name: "Molly Kiernan", email: "mollybkiernan@gmail.com" },
      { name: "PJ McCormick", email: "pj.mccormick@icloud.com" },
      { name: "Quinn Boyes", email: "qboyes@gmail.com" },
      { name: "Sean Smith", email: "seansean213@gmail.com" },
      { name: "Waleed Mansour", email: "waleedkmansour@gmail.com" },
    ],
  },
]

export function getAllPerformers(): Performer[] {
  return CONTACT_GROUPS.flatMap((g) => g.performers)
}

export function getMissingEmailPerformers(): Performer[] {
  return getAllPerformers().filter((p) => p.email === null)
}
